name: Manual Retrieve key

on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: Any key for retrieve (or create)
        required: true
      targets:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - maps.google.com
      ip:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - 127.0.0.1

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Download Hyperproof binary
        run: |
          curl -L -o hyperproof https://github.com/mr-chelyshkin/hyperproof/releases/download/v0.0.2/hyperproof-linux-amd64
          chmod +x hyperproof
      - name: GCP service account
        env:
          HYPERPROOF_GCP_SERVICE_ACCOUNT: ${{ secrets.HYPERPROOF_GCP_SERVICE_ACCOUNT }}
        run: |
          mkdir -p /tmp/gcp-service-account.json
          echo "$HYPERPROOF_GCP_SERVICE_ACCOUNT" > /tmp/gcp-service-account.json
      - name: Execute Hyperproof binary
        env:
          HYPERPROOF_AZURE_CLIENT_ID:     ${{ secrets.HYPERPROOF_AZURE_CLIENT_ID }}
          HYPERPROOF_AZURE_CLIENT_SECRET: ${{ secrets.HYPERPROOF_AZURE_CLIENT_SECRET }}
          HYPERPROOF_AZURE_TENANT_ID:     ${{ secrets.HYPERPROOF_AZURE_TENANT_ID }}
          HYPERPROOF_AZURE_VAULT_NAME:    ${{ secrets.HYPERPROOF_AZURE_VAULT_NAME }}
          HYPERPROOF_GCP_PROJECT_ID:      ${{ secrets.HYPERPROOF_GCP_PROJECT_ID }}
        run: |
          ./hyperproof \
            --gcp-key-ips ${{ inputs.ip }} \
            --gcp-key-targets ${{ inputs.targets }} \
            --key-name ${{ inputs.key }} \
            --gcp-service-account /tmp/gcp-service-account.json
