name: Manual Retrieve key

on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: Any key for retrieve (or create)
        required: true
      targets:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - maps.google.com
      ip:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - 127.0.0.1

jobs:
  retrieve:
    uses: ./.github/workflows/exec-hyperproof-retrieve.yml
    with:
      ip: ${{ inputs.ip }}
      targets: ${{ inputs.targets }}
      key: ${{ inputs.key }}
