name: Manual Retrieve key

on:
  workflow_dispatch:
    inputs:
      key:
        type: string
        description: Any key for retrieve (or create)
        required: true
      targets:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - maps.google.com
      ip:
        type: choice
        description: Harcoded some values only for test (security reason)
        required: true
        options:
          - 127.0.0.1

jobs:
  retrieve:
    uses: ./.github/workflows/exec-hyperproof-retrieve.yml
    with:
      ip: ${{ inputs.ip }}
      targets: ${{ inputs.targets }}
      key: ${{ inputs.key }}
    secrets:
      HYPERPROOF_GCP_SERVICE_ACCOUNT: ${{ secrets.HYPERPROOF_GCP_SERVICE_ACCOUNT }}
      HYPERPROOF_AZURE_CLIENT_ID: ${{ secrets.HYPERPROOF_AZURE_CLIENT_ID }}
      HYPERPROOF_AZURE_CLIENT_SECRET: ${{ secrets.HYPERPROOF_AZURE_CLIENT_SECRET }}
      HYPERPROOF_AZURE_TENANT_ID: ${{ secrets.HYPERPROOF_AZURE_TENANT_ID }}
      HYPERPROOF_AZURE_VAULT_NAME: ${{ secrets.HYPERPROOF_AZURE_VAULT_NAME }}
      HYPERPROOF_GCP_PROJECT_ID: ${{ secrets.HYPERPROOF_GCP_PROJECT_ID }}
