name: Scheduler retrieve

on:
  schedule:
    - cron: '0 * * * *'
    #- cron: '0 */6 * * *'

jobs:
  retrieve:
    uses: ./.github/workflows/exec-hyperproof-retrieve.yml
    with:
      ip: "127.0.0.1"
      targets: "maps.google.com"
      key: "GoogleMapKey"
    secrets:
      HYPERPROOF_GCP_SERVICE_ACCOUNT: ${{ secrets.HYPERPROOF_GCP_SERVICE_ACCOUNT }}
      HYPERPROOF_AZURE_CLIENT_ID: ${{ secrets.HYPERPROOF_AZURE_CLIENT_ID }}
      HYPERPROOF_AZURE_CLIENT_SECRET: ${{ secrets.HYPERPROOF_AZURE_CLIENT_SECRET }}
      HYPERPROOF_AZURE_TENANT_ID: ${{ secrets.HYPERPROOF_AZURE_TENANT_ID }}
      HYPERPROOF_AZURE_VAULT_NAME: ${{ secrets.HYPERPROOF_AZURE_VAULT_NAME }}
      HYPERPROOF_GCP_PROJECT_ID: ${{ secrets.HYPERPROOF_GCP_PROJECT_ID }}