name: retrieve GoogleMapKey

on:
  schedule:
    - cron: '0 * * * *'
    #- cron: '0 */6 * * *'

jobs:
  retrieve:
    uses: ./.github/workflows/exec-hyperproof-retrieve.yml
    with:
      ip: "127.0.0.1"
      targets: "maps.google.com"
      key: "GoogleMapKey"